### ISSUE TITLE
CIP ECO 750MG 20FCT V1 CH (Pharmacode: 2508412) ohne Preis gibt noMethod error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/sandoz.xmlconv.bbmb.ch#8]
Das Produkt hat keinen Preis: CIP ECO 750MG 20FCT V1 CH (Pharmacode: 2508412) und wirft deshalb einen noMethod error, 

http://sandoz.bbmb.ch/de/bbmb/search/query/CIP

**Comment by zdavatz** [comment]
Sieht auch so aus, als würde der GTIN fehlen. In der Bestellung ist er aber vorhanden.
![2508412](https://user-images.githubusercontent.com/4953/46445107-769e7f80-c775-11e8-9a6a-689e7e5ea882.jpg)

**Comment by zdavatz** [comment]
[99-137-20181003122920.txt](https://github.com/zdavatz/sandoz.xmlconv.bbmb.ch/files/2444388/99-137-20181003122920.txt)

**Comment by ngiger** [comment]
Spent an hour without being able to make bin/sandoz_admin to work.
Make PG 8.4 and 10.1 work for sandoz.

**Comment by zdavatz** [comment]
Woher kommt dieser NoMethod Error?

<img width="948" alt="bildschirmfoto 2018-10-13 um 09 19 45" src="https://user-images.githubusercontent.com/4953/46898994-2dfb6a80-cec9-11e8-9f5b-54dc41d8fcde.png">

**Comment by zdavatz** [comment]
Die erste Zeile im Artikel.txt enthält NON-UTF-8 Zeichen. Getestet mit:
`grep --color='auto' -P -n "[^\x00-\x7F]" Artikel.txt`

**Comment by zdavatz** [comment]
Dieser Befehl zeigt auch einen sehr interessanten Output
`sed -n 'l' Artikel.txt  | less`
ergibt
`\357\273\27744060692\tCip eco 750 mg Film Tbl 20\tCip eco 750 mg cpr \
pell 20\t7680555250209\t2508412\t36.93\r$`
für die erste Zeile. Das drückt wohl den Pharmacode nach hinten.

**Comment by zdavatz** [comment]
This seems to be the problem. See [BOM](https://stackoverflow.com/questions/1972362/why-is-my-bash-script-adding-feff-to-the-beginning-of-files)

`Vim -b` gives me `<feff>` at the beginning of the File.

**Comment by zdavatz** [comment]
werden die Daten immer überschrieben bei jedem Import? Andernfalls muss man das Produkt 2508412 neu einlesen via dem Importer, sodass die DB korrekt aktualisiert wird. Der BOM Wert ist jetzt draussen im Artikel.csv File.

**Comment by zdavatz** [comment]
Ich warte Mal auf den neusten Update.

**Comment by zdavatz** [comment]
Sieht gut aus dem dem folgenden Test.
[confuse.xml.txt](https://github.com/zdavatz/sandoz.xmlconv.bbmb.ch/files/2485240/confuse.xml.txt)
